import type { FastifyInstance } from "fastify";
import { query } from "../db/client.js";

// 20 real Oslo buildings spread across the city, covering distances from
// 0.5 km to 8 km from the Bjørvika waterfront cluster — enabling routes
// from 5 000 to 20 000 steps with accurate step-goal targeting.
const OSLO_BUILDINGS = [
  {
    name: "Nasjonalmuseet",
    short_description: "Norway's largest art museum, opened 2022. The striking building by Kleihues + Schuwerk holds 400,000 artworks including Munch's 'The Scream'.",
    description: "The National Museum of Norway opened in 2022 as one of Europe's largest art museums. Designed by German-Norwegian architects Kleihues + Schuwerk, the building's dramatic white façade and generous public spaces transformed Aker Brygge's cultural offer. The collection spans 400,000 objects from antiquity to the present, including Edvard Munch's iconic 'The Scream'.",
    architect: "Kleihues + Schuwerk",
    year_completed: 2022,
    address: "Brynjulf Bulls plass 3, Oslo",
    city: "Oslo",
    lat: 59.9167,
    lng: 10.7265,
    categories: ["civic", "new_build", "landmark"],
    era: "contemporary",
  },
  {
    name: "Nationaltheatret",
    short_description: "Norway's national theatre (1899), a grand neoclassical building at the heart of Karl Johans gate, facing the Royal Palace.",
    description: "The National Theatre opened in 1899 as a permanent home for Norwegian dramatic arts. Designed by Henrik Bull in a free Renaissance style, its façade is adorned with statues of Henrik Ibsen and Bjørnstjerne Bjørnson. The theatre hosts over 300 performances a year and sits at the symbolic centre of Norwegian cultural life.",
    architect: "Henrik Bull",
    year_completed: 1899,
    address: "Johanne Dybwads plass 1, Oslo",
    city: "Oslo",
    lat: 59.9147,
    lng: 10.7325,
    categories: ["civic", "landmark"],
    era: "neoclassical",
  },
  {
    name: "Stortinget",
    short_description: "The Norwegian Parliament (1866). Emil Victor Langlet's neoclassical yellow-brick building has been the seat of Norwegian democracy for over 150 years.",
    description: "Completed in 1866, the Storting building by Swedish architect Emil Victor Langlet is the seat of Norway's parliament. Its yellow brick façade with neoclassical details faces Karl Johans gate, the city's main boulevard. The chamber has witnessed every major decision in Norwegian history since independence in 1814.",
    architect: "Emil Victor Langlet",
    year_completed: 1866,
    address: "Karl Johans gate 22, Oslo",
    city: "Oslo",
    lat: 59.9131,
    lng: 10.7389,
    categories: ["civic", "landmark"],
    era: "neoclassical",
  },
  {
    name: "Oslo Domkirke",
    short_description: "Oslo's main cathedral, consecrated in 1697. The baroque tower has presided over the city's spiritual life for over three centuries.",
    description: "Oslo Cathedral was consecrated in 1697, though its tower dates from 1850. The interior is notable for its painted ceiling by Hugo Lous Mohr and stained glass by Emanuel Vigeland. Situated at Stortorvet, it remains the principal church of the Diocese of Oslo and a central landmark in the city's street grid.",
    architect: "Various (17th–19th c.)",
    year_completed: 1697,
    address: "Karl Johans gate 11, Oslo",
    city: "Oslo",
    lat: 59.9127,
    lng: 10.7465,
    categories: ["religious", "landmark"],
    era: "baroque",
  },
  {
    name: "Astrup Fearnley Museet",
    short_description: "Renzo Piano's 2012 contemporary art museum on Tjuvholmen, its glass sail roof a bold addition to Oslo's waterfront skyline.",
    description: "The Astrup Fearnley Museum of Modern Art opened on the Tjuvholmen peninsula in 2012 in a building designed by Renzo Piano Building Workshop. The complex of three interconnected pavilions under a dramatic glass-and-wood roof houses one of Scandinavia's finest private art collections, with works by Damien Hirst, Jeff Koons, and Cindy Sherman.",
    architect: "Renzo Piano Building Workshop",
    year_completed: 2012,
    address: "Strandpromenaden 2, Oslo",
    city: "Oslo",
    lat: 59.9090,
    lng: 10.7236,
    categories: ["new_build", "landmark", "civic"],
    era: "contemporary",
  },
  {
    name: "Nobels Fredssenter",
    short_description: "The Nobel Peace Center (2005), built in a converted 1872 railway station at Aker Brygge, celebrates Nobel Peace Prize laureates.",
    description: "The Nobel Peace Center occupies the former Vestbanen railway station (1872), sensitively converted by architect David Adjaye in 2005. The centre presents the work and thoughts of Nobel Peace Prize laureates through immersive exhibitions. Its waterfront location at Aker Brygge places it steps from Oslo City Hall, where the prize is awarded annually.",
    architect: "David Adjaye",
    year_completed: 2005,
    address: "Brynjulf Bulls plass 1, Oslo",
    city: "Oslo",
    lat: 59.9083,
    lng: 10.7267,
    categories: ["civic", "transformation"],
    era: "contemporary",
  },
  {
    name: "Mathallen Oslo",
    short_description: "A 1930s industrial hall transformed into Oslo's premier food market, where 33 artisan stalls line a stunning cast-iron interior.",
    description: "Mathallen opened in 2012 in a former industrial hall in the Vulkan development beside the Akerselva river. The cast-iron structure, originally a machine hall, now hosts 33 artisan food stalls and restaurants. The surrounding Vulkan neighbourhood is one of Oslo's most dynamic urban transformations, converting a 19th-century factory district into a cultural and gastronomic hub.",
    architect: "Lund+Slaatto Arkitekter (conversion)",
    year_completed: 2012,
    address: "Vulkan 5, Oslo",
    city: "Oslo",
    lat: 59.9256,
    lng: 10.7511,
    categories: ["transformation", "industrial_heritage"],
    era: "contemporary",
  },
  {
    name: "Gamle Aker Kirke",
    short_description: "Oslo's oldest standing building — a Romanesque stone church built around 1080, still holding services after nearly 1,000 years.",
    description: "Gamle Aker Church is Oslo's oldest building, a Romanesque stone church built around 1080, likely by King Olav Kyrre. Perched on a ridge above the city with views over the Akerselva valley, it has served the parish continuously for nearly a millennium. The thick stone walls, round arches, and austere interior are among the finest examples of medieval architecture in Scandinavia.",
    architect: "Unknown (medieval mason)",
    year_completed: 1090,
    address: "Akersbakken 26, Oslo",
    city: "Oslo",
    lat: 59.9271,
    lng: 10.7368,
    categories: ["religious", "medieval", "landmark"],
    era: "medieval",
  },
  {
    name: "Grünerløkka Brygge",
    short_description: "A 19th-century factory complex beside the Akerselva, reimagined as studios, galleries, and workshops — the heart of Oslo's creative east side.",
    description: "Grünerløkka Brygge is a cluster of late-19th century industrial buildings along the Akerselva river that have been gradually converted into studios, galleries, design offices, and independent restaurants. The area anchors Oslo's creative east side and exemplifies the city's approach to adaptive reuse — preserving industrial character while enabling contemporary creative uses.",
    architect: "Various (industrial heritage)",
    year_completed: 1895,
    address: "Grünerløkka, Oslo",
    city: "Oslo",
    lat: 59.9225,
    lng: 10.7598,
    categories: ["transformation", "industrial_heritage"],
    era: "contemporary",
  },
  {
    name: "Sofienberg Kirke",
    short_description: "A luminous yellow-brick church (1891) in Grünerløkka, its Gothic Revival silhouette rising above the neighbourhood's dense 19th-century blocks.",
    description: "Sofienberg Church was consecrated in 1891 to serve the rapidly growing working-class district of Grünerløkka. Designed by Jacob Wilhelm Nordan in a Gothic Revival style, the yellow brick exterior and slender spire are a landmark in the neighbourhood's roofscape. Inside, the light-filled nave retains much of its original decoration.",
    architect: "Jacob Wilhelm Nordan",
    year_completed: 1891,
    address: "Sofienberggata 11, Oslo",
    city: "Oslo",
    lat: 59.9222,
    lng: 10.7642,
    categories: ["religious"],
    era: "neoclassical",
  },
  {
    name: "Bislett Stadion",
    short_description: "Oslo's beloved athletics stadium, rebuilt in 2005, famous for Bislett Games world records and the city's most atmospheric football ground.",
    description: "Bislett Stadium has been an Oslo institution since 1922. The current concrete bowl, rebuilt in 2005, holds 15,000 spectators and hosts the annual Bislett Games — a Diamond League athletics meeting with a long history of world records set in Oslo's cool evening air. The surrounding Bislett neighbourhood of art nouveau apartment blocks makes this a rich architectural walk.",
    architect: "Henning Larsen (2005 rebuild)",
    year_completed: 2005,
    address: "Bislett, Oslo",
    city: "Oslo",
    lat: 59.9252,
    lng: 10.7270,
    categories: ["civic", "landmark"],
    era: "contemporary",
  },
  {
    name: "Frogner Kirke",
    short_description: "An elegant Romanesque Revival church (1907) at the gateway to Frogner Park, built in Norwegian granite with a distinctive central tower.",
    description: "Frogner Church was designed by Arnstein Arneberg in 1907 in a Romanesque Revival style using local granite. Its solid tower and arched windows complement the refined residential streets of the Frogner district. The church sits at the entrance to Frogner Park, making it a natural waypoint on any walk through Oslo's western neighbourhoods.",
    architect: "Arnstein Arneberg",
    year_completed: 1907,
    address: "Frognerplass 2, Oslo",
    city: "Oslo",
    lat: 59.9218,
    lng: 10.6989,
    categories: ["religious"],
    era: "neoclassical",
  },
  {
    name: "Vigeland Sculpture Park",
    short_description: "The world's largest sculpture park by a single artist. Gustav Vigeland's 212 bronze and granite figures explore the human condition across 80 acres.",
    description: "Vigeland Sculpture Park contains 212 sculptures in bronze, granite, and cast iron, all created by Gustav Vigeland and installed between 1924 and 1943. The monumental Monolith — a 14-metre column of 121 intertwined human figures — is surrounded by the famous Wheel of Life and the iconic Angry Boy. The park is free and open around the clock, making it Oslo's most-visited attraction.",
    architect: "Gustav Vigeland",
    year_completed: 1943,
    address: "Nobels gate 32, Oslo",
    city: "Oslo",
    lat: 59.9272,
    lng: 10.6994,
    categories: ["landmark", "civic"],
    era: "modernist",
  },
  {
    name: "Norsk Folkemuseum",
    short_description: "Scandinavia's largest open-air museum on the Bygdøy peninsula — 160 historic buildings relocated from across Norway, including a complete stave church from 1200.",
    description: "The Norwegian Folk Museum on the Bygdøy peninsula gathers 160 historic buildings relocated from around Norway, from a medieval stave church to 20th-century apartments. Founded in 1894, it is Scandinavia's largest open-air museum. A full-scale reconstruction of a 19th-century Norwegian town includes craftspeople, farm animals, and a working mill — creating a vivid portrait of Norwegian life through the centuries.",
    architect: "Various (historic buildings)",
    year_completed: 1894,
    address: "Museumsveien 10, Oslo",
    city: "Oslo",
    lat: 59.9040,
    lng: 10.6857,
    categories: ["civic", "landmark"],
    era: "medieval",
  },
  {
    name: "Vikingskipshuset",
    short_description: "Three 9th-century Viking ships in near-perfect condition, displayed in a monumental 1926 hall on Bygdøy — the finest Viking Age collection in the world.",
    description: "The Viking Ship Museum houses three 9th-century Viking longships excavated from burial mounds at Gokstad, Oseberg, and Tune. The Oseberg ship, buried in 834 AD, is the world's best-preserved Viking Age find, accompanied by elaborately carved sledges, a wagon, and textiles. The cruciform hall designed by Arnstein Arneberg in 1926 was purpose-built to display the ships at their full dramatic scale.",
    architect: "Arnstein Arneberg",
    year_completed: 1926,
    address: "Huk Aveny 35, Oslo",
    city: "Oslo",
    lat: 59.9046,
    lng: 10.6845,
    categories: ["civic", "landmark"],
    era: "neoclassical",
  },
  {
    name: "Ekebergrestauranten",
    short_description: "A 1929 functionalist restaurant on the Ekeberg ridge — Munch painted 'The Scream' on this hillside, and the view across the Oslo fjord remains breathtaking.",
    description: "Ekebergrestauranten was built in 1929 by Lars Backer in a pioneering functionalist style — one of the first major modernist buildings in Norway. The restaurant sits on the ridge where Edvard Munch experienced the sunset that inspired 'The Scream'. Today it also houses the Ekeberg Sculpture Park with works by Rodin, Dalí, and Louise Bourgeois, set among the beech forests above the city.",
    architect: "Lars Backer",
    year_completed: 1929,
    address: "Kongsveien 15, Oslo",
    city: "Oslo",
    lat: 59.8960,
    lng: 10.7769,
    categories: ["landmark"],
    era: "modernist",
  },
  {
    name: "Holmenkollen Nasjonalanlegget",
    short_description: "The world's most famous ski jump, rebuilt for the 2011 World Championships. The 65-metre tower commands a panoramic view over Oslo and the fjord.",
    description: "Holmenkollen has hosted ski jumping since 1892, making it the oldest ski jump in the world still in regular use. The current structure, redesigned by JDS Architects for the 2011 World Championships, rises 65 metres above the take-off ramp. On a clear day the view from the top encompasses Oslo, the Oslofjord, and the forests of Nordmarka. The adjacent ski museum is the world's oldest museum devoted to skiing.",
    architect: "JDS Architects",
    year_completed: 2010,
    address: "Kongeveien 5, Oslo",
    city: "Oslo",
    lat: 59.9643,
    lng: 10.6617,
    categories: ["civic", "landmark"],
    era: "contemporary",
  },
  {
    name: "Tøyenbadet",
    short_description: "A 1930s Art Deco public bathhouse in Tøyen, its terracotta tile murals and barrel-vaulted roof a rare surviving example of interwar civic architecture.",
    description: "Tøyenbadet was built in 1933 as a public indoor swimming pool for the working-class east side of Oslo. Designed in an Art Deco functionalist style, the building features terracotta tile murals depicting figures in motion, a barrel-vaulted main hall, and generous skylights. After a long closure, the bathhouse was fully restored and reopened, retaining its remarkable interwar character.",
    architect: "Harald Hals",
    year_completed: 1933,
    address: "Helgesens gate 90, Oslo",
    city: "Oslo",
    lat: 59.9169,
    lng: 10.7703,
    categories: ["civic", "industrial_heritage"],
    era: "modernist",
  },
  {
    name: "Universitetet i Oslo — Historisk Museum",
    short_description: "The University of Oslo's Historical Museum (1904), a grand jugend building housing Viking gold, Egyptian mummies, and Norway's largest coin collection.",
    description: "The Historical Museum of the University of Oslo was built in 1904 by Henrik Bull in a Jugendstil (Art Nouveau) style. The red-brick façade with organic ornamental details is one of Oslo's finest examples of the style. Inside, the collections span Norwegian prehistory, Viking Age gold treasures, Egyptian antiquities, and the world's largest Norwegian numismatic collection.",
    architect: "Henrik Bull",
    year_completed: 1904,
    address: "Frederiks gate 2, Oslo",
    city: "Oslo",
    lat: 59.9167,
    lng: 10.7394,
    categories: ["civic", "landmark"],
    era: "neoclassical",
  },
  {
    name: "Blå",
    short_description: "A converted concrete factory on the Akerselva, Oslo's most important live music venue — the industrial shell perfectly amplifies the city's independent music scene.",
    description: "Blå occupies a former concrete factory building from the early 20th century on the banks of the Akerselva river in Grünerløkka. Opened as a music venue in 1998, it quickly became the heart of Oslo's independent music scene. The raw industrial interior — exposed concrete, steel beams, high ceilings — has hosted everyone from local jazz musicians to internationally celebrated electronic artists. The adjacent outdoor terrace is a summer institution.",
    architect: "Unknown (industrial heritage)",
    year_completed: 1910,
    address: "Brenneriveien 9c, Oslo",
    city: "Oslo",
    lat: 59.9251,
    lng: 10.7561,
    categories: ["transformation", "industrial_heritage"],
    era: "contemporary",
  },
];

export async function seedRoutes(app: FastifyInstance) {
  app.post("/dev/seed-oslo", async (_req, reply) => {
    let inserted = 0;
    let skipped = 0;

    for (const b of OSLO_BUILDINGS) {
      const exists = await query(
        `SELECT id FROM buildings WHERE name = $1 AND city = $2 LIMIT 1`,
        [b.name, b.city]
      );

      if (exists.length > 0) {
        skipped++;
        continue;
      }

      await query(
        `INSERT INTO buildings (
          name, short_description, description, architect, year_completed,
          address, city, lat, lng, categories, era,
          is_verified, sources
        ) VALUES (
          $1, $2, $3, $4, $5,
          $6, $7, $8, $9, $10::building_category[], $11::building_era,
          true, '{manual}'::data_source[]
        )`,
        [
          b.name,
          b.short_description,
          b.description,
          b.architect,
          b.year_completed,
          b.address,
          b.city,
          b.lat,
          b.lng,
          `{${b.categories.join(",")}}`,
          b.era,
        ]
      );
      inserted++;
    }

    return { inserted, skipped, total: OSLO_BUILDINGS.length };
  });
}
